Kubernetes logging
otus-kuber-2020-11/itokareva_platform pull request #10
Opened 2021-01-26 17:29 UTC by itokareva

# Выполнено ДЗ №9

Сервисы централизованного логирования для компонентов Kubernetes и приложений
 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 -  Развернут кластер с помощью terraform. Скрипты для развертывания в каталоге kubernetes-logging/terraform
 -  Установлено приложение hipster
 -  Установлен EFK-стэк, prometheus, grafana, nginx-ingress, elasticsearch-exporter  с помощью helmfile
 -  В графану залит популярный дашборд для мониторинга elasticsearch
 -  Добиваемся, чтобы появились логи nginx-ingress в kibana
 -  Опробованы возможности kibana для визуализации: Visualize. Созданы визуализации для отображения запросов к
   nginx-ingress со статусами:
* 200-299
* 300-399
* 400-499
* 500+

 -  Создан дашборд с созданными визуализациями и выгружен в формате json в kubernetes-logging/export.ndjson
 -  Установлен loki с помощью helmfile
 -  создан дашборд в граафане, на котором одновременно выведем метрики nginx-ingress и его логи

 Задание со (*)
    Для централизованного просмотра централизованного логов с виртуальных машин, на которых запущен Kubernetes в
модернизирована конфигурация fluent-bit

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [HW#9] Выставил label с номером домашнего задания
 - [kubernetes-logging] Выставил label с темой домашнего задания

2021-01-26 17:58 UTC, itokareva commented
Добрый вечер, Мария, а похоже, что задание (*) неправильно выполнено: там пишутся логи по памяти и syslog контейнера, а не VM

2021-02-02 05:43 UTC, Jasstkn reviewed
> Добрый вечер, Мария, а похоже, что задание (*) неправильно выполнено: там пишутся логи по памяти и syslog контейнера, а не VM

а какие логи вам еще нужны?

2021-02-02 05:43 UTC, Jasstkn commented on kubernetes-logging/terraform/terraform.tfstate.backup
> +                "cluster_ca_certificate": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lSQU9CQXcxU3BIbzc4ZXFYYnVkR2JJVUl3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05qSTJOMlF3
Ни в коем случае не коммитьте тфстейт и бэкап в гит, у вас тут секреты плейн текстом :(
Стейт можно в гугл бакет положить и использовать его как бекенд вместо локального.
https://www.terraform.io/docs/language/settings/backends/gcs.html

2021-02-02 05:43 UTC, Jasstkn commented on kubernetes-logging/terraform/.terraform/plugins/linux_amd64/lock.json
> +{
директория .terraform в .gitignore должны быть

2021-02-02 05:43 UTC, Jasstkn requested changes
Нужно терраформ пофиксить

2021-02-02 09:24 UTC, itokareva commented
terraform пофиксила. "а какие логи вам еще нужны?" там по заданию логи VM. Это ведь не то же самое, что логи контейнера

2021-02-04 11:11 UTC, Jasstkn commented
> terraform пофиксила. "а какие логи вам еще нужны?" там по заданию логи VM. Это ведь не то же самое, что логи контейнера

ну вы можете натравить на любой лог вм - это же просто файлы

2021-02-08 08:03 UTC, Jasstkn approved these changes
Приму у вас домашнее задание, если захотите поразбираться, то сделайте новый PR - будем смотреть, что именно не получается.

2021-02-08 08:03 UTC, merged